---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: {{ .Values.namespace }}
type: Opaque 
data:
  aws_access_key_id: {{ .Values.aws_access_key_id | b64enc }} 
  aws_secret_access_key: {{ .Values.aws_secret_access_key | b64enc }}
