{{ $namespace := .Values.namespace }}
{{- range $host, $vars := .Files.Get "vars.yml" | fromYaml }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nike-{{ $host }}-secret
  namespace: "{{ $namespace }}"
type: Opaque 
data:
{{- range $key, $value := $vars }}
{{- if eq $key "time" }}
  year: {{ (split "-"  $value)._0 | b64enc }}
  month: {{ (split "-"  $value)._1 | b64enc }}
  day: {{ (split " " (split "-"  $value)._2)._0 | b64enc }}
  hour: {{ (split " " (split ":"  $value)._0)._1 | b64enc }}
  minute: {{ (split ":" $value)._1 | b64enc }}
  second: {{ (split ":" $value)._2 | b64enc }}
{{- else }}
  {{ $key }}: {{ $value | b64enc }} 
{{- end }}
{{- end }}
{{- end }}
